{% set version = "0.16.0" %}

package:
  name: bloscpack
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bloscpack/bloscpack-{{ version }}.tar.gz
  sha256: 35f440d8114e6f4c909612485fec35862019625995d79c3adb701c736e660ff5

build:
  number: 1000
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .
  entry_points:
    - blpk = bloscpack.cli:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - six
    - blosc
    - python-blosc
    - numpy

test:
  imports:
    - bloscpack
  commands:
    - blpk --help

about:
  home: https://github.com/Blosc/bloscpack
  license: MIT
  license_file: LICENSE
  summary: 'Command line interface to and serialization format for Blosc'

extra:
  recipe-maintainers:
    - danielfrg
